### ISSUE TITLE
Create Note exception

### ISSUE THREAD

**Issue by binDebug** [binDebug/TMA-Api#18]
Exception occured in CreateClientNote. Exception message is An error occurred while executing the command definition. See the inner exception for details.. Exception stack trace is -    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.Execute(EntityCommand entityCommand, CommandBehavior behavior)
    at System.Data.Entity.Core.EntityClient.EntityCommand.ExecuteReader(CommandBehavior behavior)
    at System.Data.Entity.Core.EntityClient.EntityCommand.ExecuteNonQuery()
    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteFunctionCommand(EntityCommand entityCommand)
    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
    at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass4b.<ExecuteFunction>b__49()
    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteFunction(String functionName, ObjectParameter[] parameters)
    at TMA.DAL.tmaEntities.create_client_note(Nullable`1 clientIDParam, String noteParam, Nullable`1 createdByParam, Nullable`1 isActiveParam, ObjectParameter createdId)
    at TMA.DAL.Helpers.ClientHelper.CreateClientNote(Int32 clientid, Note note)

**Comment by binDebug** [comment]
Input

[{
dateCreated: Fri Dec 07 2018 23:03:56 GMT+0530 (India Standard Time) {}
firstName: ""
id: 0
isActive: true
isDirty: true
lastName: ""
noteText: "asdasdasd"
}]

**Comment by binDebug** [comment]
For some reason, the create and update SPs were not present on my db
