### ISSUE TITLE
API - Task Put is throwing an exception

### ISSUE THREAD

**Issue by binDebug** [binDebug/TMA-Api#44]
I am trying to update only the task assignment

Input:
{"TaskId":1,"Title":"new task","Description":"new desc","TaskTypeId":1,"TaskTypeName":"PAN","TaskDueDate":"2019-03-16T18:30:00","PaymentDueDate":null,"ClientId":38,"ClientName":"kjhkj","CompanyId":0,"CompanyName":null,"Amount":null,"Status":1,"StatusName":"New","Assignments":[{"AssignmentId":1,"TaskId":1,"UserId":15,"UserName":"shilpa nagavara","UserEmail":"shilpaprabhun@gmail.com"},{"AssignmentId":0,"TaskId":1,"UserId":16,"UserName":null,"UserEmail":null}],"Documents":[],"Notes":[]}

Exception:
Exception occured in UpdateTask. Exception message is An error occurred while executing the command definition. See the inner exception for details.. Exception stack trace is -    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.Execute(EntityCommand entityCommand, CommandBehavior behavior)
    at System.Data.Entity.Core.EntityClient.EntityCommand.ExecuteReader(CommandBehavior behavior)
    at System.Data.Entity.Core.EntityClient.EntityCommand.ExecuteNonQuery()
    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteFunctionCommand(EntityCommand entityCommand)
    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
    at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass4b.<ExecuteFunction>b__49()
    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteFunction(String functionName, ObjectParameter[] parameters)
    at TMA.DAL.tmaEntities.update_task(Nullable`1 taskIdParam, String taskTitleParam, String taskDescriptionParam, Nullable`1 taskTypeIdParam, Nullable`1 taskDueDateParam, Nullable`1 taskStatusParam, Nullable`1 clientIdParam, Nullable`1 companyIDParam, Nullable`1 amountParam, Nullable`1 updatedByParam)
    at TMA.DAL.Helpers.TaskHelper.UpdateTask(TMATask task)

**Comment by binDebug** [comment]
So, the root of this issue is that Get task by task id is not returning company id. Can you please fix this?

**Comment by binDebug** [comment]
I deployed the latest delta file and it still is throwing an exception
Input:

Input data: {"TaskId":2,"Title":"enw task 1","Description":"new desc","TaskTypeId":1,"TaskTypeName":"PAN","TaskDueDate":"2019-03-17T18:30:00","PaymentDueDate":"2019-03-18T00:00:00","ClientId":1,"ClientName":"TestClient1","CompanyId":1,"CompanyName":null,"Amount":null,"Status":1,"StatusName":"New","Assignments":[{"AssignmentId":0,"TaskId":2,"UserId":1,"UserName":null,"UserEmail":null},{"AssignmentId":0,"TaskId":2,"UserId":16,"UserName":null,"UserEmail":null}],"Documents":[],"Notes":[]}
--

Exception:
System.FormatException: Input string was not in a correct format.
    at System.Text.StringBuilder.FormatError()
    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
    at System.String.Format(String format, Object arg0, Object arg1)
    at TMA.RestAPI.Controllers.TasksController.UpdateAssignments(TMATask task, TaskHelper taskHelper, TMATask taskCurrent)
    at TMA.RestAPI.Controllers.TasksController.UpdateTask(TMATask task)
