### ISSUE TITLE
API - Delete payment throwing exception

### ISSUE THREAD

**Issue by binDebug** [binDebug/TMA-Api#63]
1. Add payment to task
2. Delete payment.
Exception:

Exception occured in UpdateTaskPayment. Exception message is An error occurred while executing the command definition. See the inner exception for details.. Exception stack trace is -    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.Execute(EntityCommand entityCommand, CommandBehavior behavior)
    at System.Data.Entity.Core.EntityClient.EntityCommand.ExecuteReader(CommandBehavior behavior)
    at System.Data.Entity.Core.EntityClient.EntityCommand.ExecuteNonQuery()
    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteFunctionCommand(EntityCommand entityCommand)
    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
    at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass4b.<ExecuteFunction>b__49()
    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteFunction(String functionName, ObjectParameter[] parameters)
    at TMA.DAL.tmaEntities.update_task_payment(Nullable`1 paymentIdParam, Nullable`1 taskIdParam, Nullable`1 partAmountParam, Nullable`1 paymentModeIdParam, Nullable`1 targetAccountIdParam, String taskPaymentParticularsParam, Nullable`1 updatedByParam, Nullable`1 isActiveParam)
    at TMA.DAL.Helpers.TaskHelper.UpdateTaskPayment(TaskPayment taskPayment)

**Comment by binDebug** [comment]
Can you please provide the SP for task payment update that is on your machine? I have the same version that is in super-delta and I'm still getting the error.

**Comment by binDebug** [comment]
Again, here, the targetaccountid is being passed as 0 to the SP. And that is breaking the referential integrity constraint with target account table.

The reason the targetaccountid is 0 is because the get task is returning 0
![image](https://user-images.githubusercontent.com/17793833/56031360-e604b580-5d3c-11e9-82ee-5da691100413.png)

If this is fixed, this issue should go away.
