### ISSUE TITLE
API - Create payment (cash) is throwing an exception

### ISSUE THREAD

**Issue by binDebug** [binDebug/TMA-Api#70]
Input:
{"TaskPaymentId":0,"TaskId":12,"Amount":90.0,"PaymentModeId":47,"PaymentMode":null,"TargetAccountId":0,"TargetAccount":null,"TargetAccountName":null,"Particulars":"","DateCreated":"0001-01-01T00:00:00","IsActive":null}

Exception:
Exception occured in CreateTaskPayment. Exception message is An error occurred while executing the command definition. See the inner exception for details.. Exception stack trace is -    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.Execute(EntityCommand entityCommand, CommandBehavior behavior)
    at System.Data.Entity.Core.EntityClient.EntityCommand.ExecuteReader(CommandBehavior behavior)
    at System.Data.Entity.Core.EntityClient.EntityCommand.ExecuteNonQuery()
    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteFunctionCommand(EntityCommand entityCommand)
    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
    at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass4b.<ExecuteFunction>b__49()
    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteFunction(String functionName, ObjectParameter[] parameters)
    at TMA.DAL.tmaEntities.create_task_Payment(Nullable`1 taskIdParam, Nullable`1 partAmountParam, Nullable`1 paymentModeIdParam, Nullable`1 targetAccountIdParam, String taskPaymentParticularsParam, Nullable`1 createdByParam, ObjectParameter createdId)
    at TMA.DAL.Helpers.TaskHelper.CreateTaskPayment(Int32 taskId, TaskPayment taskPayment)

**Comment by binDebug** [comment]
This is because for cash, the target account is not requried. I think the table/SP needs to be updated to allow null for target account id.
